language: erlang
services: postgresql
addons:
  postgresql: "9.6"
otp_release:
  - 20.2
  - 20.1
  - 20.0
  - 19.3
  - 19.2
  - 19.1
  - 19.0
script:
  - rebar3 ct --config travis.ctc
after_success:
  - rebar3 as test coveralls send
